#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# OneMoreGift · DreamHost deploy script (runs ON the server)
#
# Invoked by .github/workflows/deploy-production.yml, which pipes this file over
# SSH: it never has to pre-exist on the server. You can also run it by hand:
#
#     bash deploy/dreamhost/deploy.sh
#
# What it does: sync the production branch, install backend deps, build the
# frontend, then restart the app(s). Two restart models are supported:
#   - pm2 (default): DreamHost Managed VPS/Dedicated. The panel's Proxy Server
#     forwards the domain to FRONTEND_PORT and /api/v1 to the backend (9000).
#     DreamHost shared hosting cannot run Node.js at all.
#   - passenger: legacy; DreamHost no longer supports Passenger for Node 14+.
#
# Configuration (all optional; sane defaults). Set via env / GitHub secrets:
#   APP_DIR           Repo checkout on the server        (default: $HOME/onemoregift)
#   DEPLOY_BRANCH     Branch to deploy                   (default: production)
#   RESTART_MODE      pm2 | passenger                    (default: pm2)
#   FRONTEND_PORT     Port Next.js listens on under pm2  (default: 8000; the
#                     DreamHost Proxy Server only forwards to 8000-65535)
#   API_HOST          Public API origin baked into the FE build
#                                                        (default: https://onemoregift.in)
#   BACKEND_APP_DIR   Passenger app dir for the API      (default: $HOME/api.onemoregift.in)
#   FRONTEND_APP_DIR  Passenger app dir for the frontend (default: $HOME/onemoregift.in)
#   SKIP_BUILD        1 to skip the frontend build       (default: 0)
# ─────────────────────────────────────────────────────────────────────────────

# Make node/npm/git resolvable under a non-interactive SSH session (nvm, etc.).
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" >/dev/null 2>&1 || true
export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH"

APP_DIR="${APP_DIR:-$HOME/onemoregift}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-production}"
RESTART_MODE="${RESTART_MODE:-pm2}"
export FRONTEND_PORT="${FRONTEND_PORT:-8000}"
API_HOST="${API_HOST:-https://onemoregift.in}"
BACKEND_APP_DIR="${BACKEND_APP_DIR:-$HOME/api.onemoregift.in}"
FRONTEND_APP_DIR="${FRONTEND_APP_DIR:-$HOME/onemoregift.in}"
SKIP_BUILD="${SKIP_BUILD:-0}"

log() { printf '\n\033[1;36m[deploy]\033[0m %s\n' "$*"; }
die() { printf '\n\033[1;31m[deploy] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v git  >/dev/null || die "git not found on PATH"
command -v node >/dev/null || die "node not found on PATH (configure Node/nvm for this shell)"
command -v npm  >/dev/null || die "npm not found on PATH"
[ -d "$APP_DIR/.git" ] || die "APP_DIR '$APP_DIR' is not a git checkout. Clone the repo there first (see deploy/dreamhost/README.md)."

log "Node $(node -v) · npm $(npm -v)"

log "Sync '$DEPLOY_BRANCH' in $APP_DIR"
cd "$APP_DIR"
git fetch --all --prune
git checkout "$DEPLOY_BRANCH"
# Match the remote exactly — deploys must be reproducible, not a fragile merge.
git reset --hard "origin/$DEPLOY_BRANCH"

log "Install backend dependencies"
cd "$APP_DIR/backend"
npm ci --omit=dev
mkdir -p public/uploads/images

if [ "$SKIP_BUILD" = "1" ]; then
  log "SKIP_BUILD=1 — skipping frontend build"
else
  log "Build frontend (Next.js standalone)"
  cd "$APP_DIR/frontend"
  npm ci
  NEXT_PUBLIC_BASE_URL="$API_HOST/api/v1/" \
  NEXT_PUBLIC_API_URL="$API_HOST/api/v1" \
  NEXT_PUBLIC_ALTCHA_CHALLENGE_URL="$API_HOST/api/altcha/challenge" \
  BACKEND_INTERNAL_URL="http://127.0.0.1:9000" \
  npm run build
fi

if [ "$RESTART_MODE" = "pm2" ]; then
  command -v pm2 >/dev/null || die "RESTART_MODE=pm2 but pm2 is not installed"
  log "Restart via PM2 (frontend on :$FRONTEND_PORT, backend on :9000)"
  cd "$APP_DIR"
  pm2 startOrReload ecosystem.config.cjs --update-env || pm2 start ecosystem.config.cjs
  pm2 save
  log "Deploy finished (pm2)."
  exit 0
fi

# ── Passenger model ──────────────────────────────────────────────────────────
# Each app runs from its own directory whose `app.js` is Passenger's entry point.
# We keep those entry dirs SEPARATE from the repo so nothing in the repo is
# overwritten (the backend already ships its own app.js module).

log "Wire up backend Passenger app dir: $BACKEND_APP_DIR"
mkdir -p "$BACKEND_APP_DIR/tmp"
# app.js just boots the repo's Express server (index.js listens on process.env.PORT,
# which Passenger provides). __dirname stays the repo, so .env/public resolve there.
cat > "$BACKEND_APP_DIR/app.js" <<JS
// Auto-generated by deploy.sh — Passenger entry point for the API.
require('$APP_DIR/backend/index.js');
JS
# Serve uploaded media straight from the repo's public dir.
if [ ! -e "$BACKEND_APP_DIR/public" ]; then
  ln -s "$APP_DIR/backend/public" "$BACKEND_APP_DIR/public"
fi

log "Assemble frontend standalone into: $FRONTEND_APP_DIR"
mkdir -p "$FRONTEND_APP_DIR/.next/static" "$FRONTEND_APP_DIR/public" "$FRONTEND_APP_DIR/tmp"
cp -R "$APP_DIR/frontend/.next/standalone/." "$FRONTEND_APP_DIR/"
cp -R "$APP_DIR/frontend/.next/static/." "$FRONTEND_APP_DIR/.next/static/"
cp -R "$APP_DIR/frontend/public/." "$FRONTEND_APP_DIR/public/"
[ -f "$APP_DIR/frontend/.env.production" ] && cp "$APP_DIR/frontend/.env.production" "$FRONTEND_APP_DIR/.env.production" || true
# Passenger entry: the Next standalone server (reads process.env.PORT from Passenger).
cat > "$FRONTEND_APP_DIR/app.js" <<'JS'
// Auto-generated by deploy.sh — Passenger entry point for the Next.js frontend.
require('./server.js');
JS

log "Restart Passenger apps"
touch "$BACKEND_APP_DIR/tmp/restart.txt"
touch "$FRONTEND_APP_DIR/tmp/restart.txt"

log "Deploy finished (passenger)."
